# Generated by Django 5.1.7 on 2025-03-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypiproject',
            name='component',
            field=models.CharField(default='Default Component', max_length=200),
        ),
    ]
