# Generated by Django 5.1.7 on 2025-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_raspberrypiproject_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinoproject',
            name='component',
            field=models.CharField(default='Default Component', max_length=200),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='component',
            field=models.CharField(default='Default Component', max_length=200),
        ),
    ]
