# Generated by Django 5.1.7 on 2025-03-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_arduinoproject_component_nodemcuproject_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinoproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
        migrations.AlterField(
            model_name='arduinoproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AlterField(
            model_name='nodemcuproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AlterField(
            model_name='raspberrypiproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
    ]
