# Generated by Django 5.1.7 on 2025-03-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_arduinoproject_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinoproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
    ]
