# Generated by Django 5.1.7 on 2025-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_arduinoproject_image2_nodemcuproject_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arduinoproject',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='nodemcuproject',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='raspberrypiproject',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='description2',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='description2',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='description2',
            field=models.TextField(default='Default Description'),
        ),
    ]
