# Generated by Django 5.1.7 on 2025-04-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_description_arduinoproject_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arduinoproject',
            old_name='image',
            new_name='title_image',
        ),
        migrations.RenameField(
            model_name='nodemcuproject',
            old_name='image',
            new_name='title_image',
        ),
        migrations.RenameField(
            model_name='raspberrypiproject',
            old_name='image',
            new_name='title_image',
        ),
    ]
