# Generated by Django 5.1.7 on 2025-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_image_arduinoproject_title_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinoproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='arduinoproject',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='nodemcuproject',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
        migrations.AddField(
            model_name='raspberrypiproject',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Nodeproli/'),
        ),
    ]
