# Generated by Django 5.1.7 on 2025-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_arduinoproject_image3_arduinoproject_image4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinoproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AlterField(
            model_name='arduinoproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AlterField(
            model_name='arduinoproject',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AlterField(
            model_name='arduinoproject',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='ardproli'),
        ),
        migrations.AlterField(
            model_name='raspberrypiproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
        migrations.AlterField(
            model_name='raspberrypiproject',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
        migrations.AlterField(
            model_name='raspberrypiproject',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
        migrations.AlterField(
            model_name='raspberrypiproject',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='rasprojectsli/'),
        ),
    ]
