# Generated by Django 5.1.7 on 2025-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_arduinoproject_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinoproject',
            name='image6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ardproli'),
        ),
    ]
