# Generated by Django 5.1.7 on 2025-04-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_arduinoproject_image6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduinoproject',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='nodemcuproject',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='raspberrypiproject',
            name='image6',
        ),
    ]
