# Generated by Django 5.1.7 on 2025-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_arduinoproject_image6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenAIProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('description2', models.TextField(default='Default Description')),
                ('Requirements', models.CharField(default='Default Component', max_length=200)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='ardproli')),
            ],
        ),
        migrations.CreateModel(
            name='WebDevelopmentprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('description2', models.TextField(default='Default Description')),
                ('Requirements', models.CharField(default='Default Component', max_length=200)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='ardproli')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='ardproli')),
            ],
        ),
        migrations.DeleteModel(
            name='NodemcuProject',
        ),
        migrations.DeleteModel(
            name='RaspberryPiProject',
        ),
        migrations.RemoveField(
            model_name='arduinoproject',
            name='Price',
        ),
    ]
