# Generated by Django 5.1.7 on 2025-04-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_genaiprojects_webdevelopmentprojects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genaiprojects',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='genaiprojects',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='webdevelopmentprojects',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='webdevelopmentprojects',
            name='image5',
        ),
    ]
