# Generated by Django 5.1.7 on 2025-04-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_genaiprojects_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('Requirements', models.CharField(default='Default Component', max_length=200)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='ardproli')),
            ],
        ),
        migrations.DeleteModel(
            name='GenAIProjects',
        ),
        migrations.RemoveField(
            model_name='arduinoproject',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='arduinoproject',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='arduinoproject',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='arduinoproject',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='arduinoproject',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='webdevelopmentprojects',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='webdevelopmentprojects',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='webdevelopmentprojects',
            name='image3',
        ),
    ]
