# Generated by Django 5.1.7 on 2025-04-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
