# Generated by Django 5.1.7 on 2025-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_internship_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
