# Generated by Django 5.1.7 on 2025-04-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_internship_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='course',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='timestamp',
        ),
    ]
